### ISSUE TITLE
Providing minimum versions for dependencies is recommended

### ISSUE THREAD

**Issue by rsokl** [naver/kapture#1]
Hi all, thank you for sharing your code with everyone! 

A mild request / comment. It is generally considered to be good practice to specify minimum versions in your [`install_requires`](https://github.com/naver/kapture/blob/f9a4808849dd83afeeae8b79232bf6cfa4b725bc/setup.py#L60-L72), especially when you can expect users to be using conda. 

For instance, unless a conda environment already has the latest version of numpy - as available on pypi - installing your package will install the latest version of numpy _on top of the conda-supplied numpy_. Not only does this lead to a mess, but no longer will the user benefit from the MKL-optimized numpy provided by conda.

**Comment by nguerin** [comment]
Hi!
Thanks for the comment and suggestion. 
It is not always easy to know what would be the minimum version supported, but we can at least specify the current version.
We will fix this quickly.

**Comment by rsokl** [comment]
True, but it is often pretty easy to hazard a guess by glancing at the changelogs of the library. Then you can run your tests against an environment with those guessed minimal versions to verify. That provides people with some "head room".

**Comment by rsokl** [comment]
I hope this was helpful! I think this will make it easier for people to include `kapture` in their dev and deployment workflows

**Comment by nguerin** [comment]
Thanks for your remark! We updated the setup.py to specify minimal versions (1c13558)
A new release 1.0.8 is now available.
