### ISSUE TITLE
About inloc 3d lidar scan

### ISSUE THREAD

**Issue by shamangary** [naver/kapture#13]
Hello,

In the doc, it says there is a readme_kapture.txt to show how to use 3d scan in the kapture pipeline.
However, I didn't see it anywhere. Would you mind to point out some direction of how to use this with 3d scan data in inloc dataset evaluation? Thanks

**Comment by humenbergerm** [comment]
Hi!

Did you download the kapture version of the dataset?

Best,
Martin

**Comment by shamangary** [comment]
My bad :). Dataset was downloaded long time ago. Thanks.
