### ISSUE TITLE
matches-vs-inliers and F/E matrices

### ISSUE THREAD

**Issue by ducha-aiki** [naver/kapture#17]
Hi,

Is there any way to store both tentative matches (which can be wrong) and inliers (after RANSAC, but not yet sure  3D observations)?
And, related to this - is there a plan for storing intermediate pairwise image relationships, like essental/findamental matrices? I can prepare a PR for this.

Best, Dmytro

**Comment by yocabon** [comment]
Hi, 
for matches, what you call inliers is what we call matches with geometric verification in kapture-localization.
There is no way to have both tentative matches and inliers within the same kapture but what we do is to have one kapture with the tentative matches and one with the inliers. In practice, we store all the matches in an 'orphan' folder, detached from kapture, and the kapture folders are built with symlinks.
see https://github.com/naver/kapture-localization/blob/1.1_draft/doc/tutorial.adoc#recommended-dataset-structure

For intermediate pairwise image relationships (essental/findamental matrices), we have no intention of adding them to the format right now.

--
Yohann

**Comment by ducha-aiki** [comment]
Hi,

Thank you for the quick answer. I will try to do the thing with two kaptures for tentative matches. 

Regarding F/E, I hope that you will reconsider at some point. 
For example, of the use-cases I have in mind is to use kapture as The format for the 3d reconstruction, e.g for this our paper
https://arxiv.org/abs/2011.11986

Without F/E relations, one cannot use kapture as a representation for SfM system (so that SfM system is build around kapture format). Then one has to mix it with other, handcoded formats, which kind of defy idea of the kapture as universal format.

**Comment by humenbergerm** [comment]
Hi!

Thanks for the question and comment. At the moment, we use kapture mainly for visual localization and we added reconstruction data that is often used in such algorithms. However, we are currently considering adding something a bit more generic that could be used to store F/E matrices or other algorithms specific data.

Best,
Martin

**Comment by jujumo** [comment]
Issue seem resolved. Please reopen if needed.
