### ISSUE TITLE
About the ScanNet dataset

### ISSUE THREAD

**Issue by atztao** [naver/kapture#19]
This project can be used the RGB-D image and camera pose of the ScanNet to generate the ground truth of the match pairs？

**Comment by humenbergerm** [comment]
Hi! 

Kapture can be used for datasets that contain RGB-D data. Note that this repository is all about the data format specification and the tools to use it (I/O, converters, etc.). If you want to process the datasets, you need to write you own code or use tools that are directly supported by kapture, such as COLMAP or OpenMVG.
We also have a repository with algorithms for visual localization, just in case this might help you.
https://github.com/naver/kapture-localization

Best,
Martin

**Comment by atztao** [comment]
> Hi!
> 
> Kapture can be used for datasets that contain RGB-D data. Note that this repository is all about the data format specification and the tools to use it (I/O, converters, etc.). If you want to process the datasets, you need to write you own code or use tools that are directly supported by kapture, such as COLMAP or OpenMVG.
> We also have a repository with algorithms for visual localization, just in case this might help you.
> https://github.com/naver/kapture-localization
> 
> Best,
> Martin

Thanks.
