### ISSUE TITLE
How can I get global features from dataset

### ISSUE THREAD

**Issue by kmy8800** [naver/kapture#2]
I extracted descriptors and keypoints from virtual gallery dataset using R2D2.

But I don't know how to extract global features.

**Comment by nguerin** [comment]
Hi,
You're right, the documentation does not mention this yet, but we will complete it.
In the meantime, you should use the ApGem code at https://github.com/yocabon/deep-image-retrieval/
Please have a look at https://github.com/yocabon/deep-image-retrieval#feature-extraction-with-kapture-datasets for more details.
Thanks!

**Comment by nguerin** [comment]
Updated the documentation (8248273)

**Comment by nguerin** [comment]
I also added information about D2-Net (local feature) 10569ad

**Comment by kmy8800** [comment]
Thanks!!! I'll try :)

**Comment by kmy8800** [comment]
It works!! Thank you!
