### ISSUE TITLE
Permissions for scripts and dos formatting

### ISSUE THREAD

**Issue by mingu6** [naver/kapture#22]
Hi,

Thanks for all of your great work on this! I have a minor bug to report around the scripts in the tools/ folder.  I am running Ubuntu 20.04 and have installed Kapture through pip using an empty conda environment with python=3.7.

Two issues:

1.  all scripts in the tools/ folder, e.g. kapture_download_dataset.py are not executable upon installation. I can manually fix this of course, but not ideal every time Kapture is installed/updated.
`kapture_download_dataset.py update`
`zsh: permission denied: kapture_download_dataset.py`
2.  After making the script executable within the package directory, executing the script again yields the following error:
`kapture_download_dataset.py update`
`/usr/bin/env: ‘python3\r’: No such file or directory`
This is due to special characters or something through Windows or something. I can again easily fix this by running dos2unix on all tools but again this is suboptimal every time kapture is installed/updated.

Is there any way to address this for future releases? I remember a few releases ago this was not an issue.

**Comment by yocabon** [comment]
Hi, this might be because I pushed the release to pip this time and I work on windows.
There shouldn't be a problem with the files from the repository (I check they are 755, except a few that I fixed, and I don't get the error when I try to run them on our linux server) so we'll take a look and probably re-upload the release.

**Comment by nguerin** [comment]
Hi,
We fixed the package so that the scripts are now directly executable when installed with pip.
You can directly use the newer version (1.1.1).
Thanks for your feedback!

**Comment by mingu6** [comment]
Works a treat, thanks! Keep up the great work :)
