### ISSUE TITLE
Using custom local keypoints and descriptors

### ISSUE THREAD

**Issue by charlesyuJY** [naver/kapture#23]
Hi,
I am trying to replace the keypoints generated by R2D2 with keypoints generated by other custom local feature extraction methods. Just wondering, if this is possible on Kaputer? My approach is to prepare the keypoint folder and descriptor folder using the same structure provided by Kapture.

I will appreciate it a lot if you can let me know if this approach is feasible.

Thank you very much! Best!

**Comment by yocabon** [comment]
Hi,
of course it is possible to use kapture with local features other than r2d2, we've used it with d2net, SIFT, ASLFeat to cite a few.
You just have to make sure your extracted features follow our specifications https://github.com/naver/kapture/blob/main/kapture_format.adoc#reconstruction-1.
