### ISSUE TITLE
point clouds of datasets are missing

### ISSUE THREAD

**Issue by SiauYau** [naver/kapture#24]
Hi there, I've just downloaded your greate datasets in crowded indoor spaces. But after decompressed, I found only the images and dpeths file in mapping directories while the point clouds are missing.
Am I doing something wrong or do I need to reconstruct the point clouds follwing kapture-localization mapping pipeline?

**Comment by humenbergerm** [comment]
Hi!

The depth maps are created using the lidar points. We do not provide the complete lidar point cloud (too big). If you need a lidar point cloud, you can project the 2.5D points of the depth maps into 3D space using the intrinsics and extrinsic camera parameters. If you need an SFM point cloud, i.e. triangulated keypoint matches, you can follow the kapture-localization pipeline. I hope this helps.

Best,
Martin

**Comment by SiauYau** [comment]
> 
> 
> Hi!
> 
> The depth maps are created using the lidar points. We do not provide the complete lidar point cloud (too big). If you need a lidar point cloud, you can project the 2.5D points of the depth maps into 3D space using the intrinsics and extrinsic camera parameters. If you need an SFM point cloud, i.e. triangulated keypoint matches, you can follow the kapture-localization pipeline. I hope this helps.
> 
> Best,
> Martin

OK, I got it. Thanks for you reply.

**Comment by SiauYau** [comment]
@humenbergerm :
I am trying to convert .depth file to a depth map image through records_depth_from_file() method supplied in kapture/io/records.py, and it needs a array size for input. Refer to the link(https://github.com/naver/kapture/blob/main/kapture_format.adoc#records_data-depth) , it says "The size of the array is specified in the sensor parameters (sensors.txt)". But  from the sensors.txt which located in 'release\mapping\sensors' I didn't find the array size mentioned above.
Here is a snippet of the sensors.txt:
>40027089_01_depth, , depth, OPENCV, 864, 682, 571.597290561976, 581.1253129959712, 433.9607026840422, 338.53409232523006, -0.15946795500933494, 0.08979751032228203, 0.0007017143411966833, 0.00015064534071406845

**Comment by humenbergerm** [comment]
Hi!

sensors.txt is explained here: https://github.com/naver/kapture/blob/main/kapture_format.adoc#camera--depth
In your case the size (width and height) is 864 and 682.

Best,
Martin

**Comment by SiauYau** [comment]
@humenbergerm Thanks. I will try it again.
