### ISSUE TITLE
inloc mapping image poses calculation

### ISSUE THREAD

**Issue by Grem-Lin** [naver/kapture#26]
How did you calculate mapping image's pose in file InLoc_wo_images/mapping/sensors/trajectories.txt? Thanks!

**Comment by mhumenbe** [comment]
Hi! We received these poses from the dataset owners. However, they have been computed by applying the rotations of the cutouts to the given poses (https://github.com/HajimeTaira/InLoc_dataset). Best, Martin

**Comment by Grem-Lin** [comment]
Hi thanks for the quick reply! What do you mean by "applying the rotations of the cutouts to the given poses"? Based on what I have learned from inloc dataset, they only provided 3D alignment calculated by GICP for each folder, for example inloc/database/cutouts/DUC1/000.

**Comment by mhumenbe** [comment]
Yes, they provide a pose for each folder. The image names then define the transforms for each cutout. See this file: https://github.com/HajimeTaira/InLoc_demo/blob/master/functions/wustl_function/P_db.m

Since this a bit complicated, we directly provide the converted poses for convenience :)

**Comment by Grem-Lin** [comment]
Hi thanks for pointing this code to me. I think I understand how they calculated the poses, like playing with a bunch of transformations between many coordinate systems. Actually the reason why I asked this question is that there is an obvious difference (about 0-0.5m on translation) between inloc provided pose (you pointed to me) and pose directly calculated by pnp method using all 2D points from image and the corresponding 3D points. Did you met this issue before? Thanks!

**Comment by mhumenbe** [comment]
I have not done such an experiment but I am looking forward to hear more about it.

**Comment by Grem-Lin** [comment]
Thanks! Let me ask Inloc author and get it back to you then. Thank again!

**Comment by Grem-Lin** [comment]
Hi I studied this with Inloc authors, and they confirmed that their database pose GT has slight error on translation. The error is introduced when they built RGB images (XXX.jpg) and point clouds (XXX.mat) from raw scans. They told me that a better pose GT can be calculated by PnP with all 2D points from image and the corresponding 3D points (as what I did above). So, you may want to re-do pose GTs. Thanks!
