### ISSUE TITLE
Bug: visual studio doesn't import relative paths in kapture/io/csv.py

### ISSUE THREAD

**Issue by szeliski** [naver/kapture#28]
The following two lines in `csv.py` cause Visual Studio Code to crash (fails to run):

    from .tar import KAPTURE_TARABLE_TYPES, TarCollection, TarHandler
    from .tar import get_feature_tar_fullpath, retrieve_tar_handler_from_collection

The fix is to use absolute paths:

    from kapture.io.tar import KAPTURE_TARABLE_TYPES, TarCollection, TarHandler
    from kapture.io.tar import get_feature_tar_fullpath, retrieve_tar_handler_from_collection

**Comment by jujumo** [comment]
We extensively use VS Code, but never had this problem. And thus, we cant reproduce this error.
Could you give the context of the error ? Are you trying to import csv directly from custom code ?

Anyway, absolute path seems better in any case, I'll will apply this change. 
But I am afraid there are a lot more relative imports. So, if you encounter this kind of error, let me know, I'll do a more thorough pass.

**Comment by szeliski** [comment]
Thanks.  I tried to reproduce the bug this morning but it didn't occur.  (I pulled the latest code but restored the relative
    from .tar import
to the way it was yesterday, and tried re-running kapture_print, but nothing bad happened.

So it may be the way I invoked the code.  Thanks, anyway.
