### ISSUE TITLE
Issue with setting up Kapture.

### ISSUE THREAD

**Issue by kjyothiswaroop** [naver/kapture#29]
Hello Everyone!

I was setting up kapture on my system Ubuntu 18.04 using docker. 

I was using this Instructions page :
[Installation](https://github.com/naver/kapture/blob/main/doc/installation.adoc)

In this the installation  shows no issues.

But while running the command in Section 4. test your installation:

`python3 ./kapture_print.py -i ../samples/Aachen-Day-Night/kapture/training`

This line throws an error as shown in the image below:

![Kapture_Githubissue](https://user-images.githubusercontent.com/51844889/129844123-8d2a2226-52fc-4d55-9fd3-a8123b6b31f9.png)

The error reads : 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

What can I do to correct this?

**Comment by jujumo** [comment]
thanks for mentioning it. It should works with latest Dockerfile (setup to UTF-8 now).
