### ISSUE TITLE
Subprocess Error (Return code: -9 ) while bundle adjustment

### ISSUE THREAD

**Issue by kmy8800** [naver/kapture#3]
When I run code at tutorial(https://github.com/naver/kapture/blob/master/doc/tutorial.adoc) 

**Custom local features and matching based on image retrieval** 

3) Build map using COLMAP

`kapture_colmap_build_map.py -v info -i ./mapping --pairsfile-path ./tutorial/mapping_pairs.txt \
                            -o ./tutorial/mapping_colmap --use-colmap-matches-importer \
                            --Mapper.ba_refine_focal_length 0 \
                            --Mapper.ba_refine_principal_point 0 \
                            --Mapper.ba_refine_extra_params 0`  

some error occurs.

> ==============================================================================
Retriangulation
==============================================================================
  => Completed observations: 1261026
  => Merged observations: 44269393
==============================================================================
Bundle adjustment
==============================================================================
Traceback (most recent call last):
  File "/home/hms/anaconda3/envs/kapture/bin/kapture_colmap_build_map.py", line 247, in <module>
    colmap_build_map_command_line()
  File "/home/hms/anaconda3/envs/kapture/bin/kapture_colmap_build_map.py", line 243, in colmap_build_map_command_line
    args.skip, args.force)
  File "/home/hms/anaconda3/envs/kapture/bin/kapture_colmap_build_map.py", line 62, in colmap_build_map
    force)
  File "/home/hms/anaconda3/envs/kapture/bin/kapture_colmap_build_map.py", line 157, in colmap_build_map_from_loaded_data
    point_triangulator_options
  File "/home/hms/anaconda3/envs/kapture/lib/python3.6/site-packages/kapture/converter/colmap/colmap_command.py", line 242, in run_point_triangulator
    run_colmap_command(colmap_binary_path, point_triangulator_args)
  File "/home/hms/anaconda3/envs/kapture/lib/python3.6/site-packages/kapture/converter/colmap/colmap_command.py", line 37, in run_colmap_command
    '\nSubprocess Error (Return code:'
ValueError: 
Subprocess Error (Return code: -9 )

Does it occur because of lack of GPU memory, or something?

Please tell me....

One more question is, how long does it take to do 'bundle adjustment'?

It took more than 10 hours with 14600 train images and 4000 test images. (i7-9700k, RTX 2060)

**Comment by nguerin** [comment]
Hello,
This error means that COLMAP fails during the Bundle Adjustment phase, indeed. There may be several reasons for this.
Are you running this tutorial: https://github.com/naver/kapture/blob/master/doc/tutorial.adoc#standard-colmap-pipeline-sift-local-features-and-vocabulary-tree-matching ?
What dataset are you using? You may want to try the pipeline on a small dataset first (eg. the virtual_gallery_tutorial): it will be much faster.

To investigate the error, you can also run the command-line in verbose mode (e.g. debug) to get the actual colmap command, and test it separately.

Last, the Bundle Adjustment phase of COLMAP can be very slow indeed for larger datasets, so the numbers you provide are not surprising.

**Comment by kmy8800** [comment]
Thanks for comment!

Actually I running tutorial : https://github.com/naver/kapture/blob/master/doc/tutorial.adoc#custom-local-features-and-matching-based-on-image-retrieval

with Virtual Gallery dataset, not the whole, only a part(loop1, loop2)

I'll try another tutorial(SIFT pipeline), and ask again if I have any questions. Thank you!!

**Comment by nguerin** [comment]
Hi,
The Virtual Gallery dataset is quite large. The sample provided in samples/virtual_gallery_tutorial is much smaller: maybe you should start with this one.

**Comment by kmy8800** [comment]
I completed tutorial with SIFT! Thanks!

I want to know 6d pose of camera when an input image(not in train&test dataset)  is given.

How can I do this?

**Comment by jujumo** [comment]
Hi, 

Great news !
You'll find the poses in `sensors/trajectories.txt`.
The rotation quaternion and the translation vector describe the transformation from world to device (same as in colmap).
see: [specs](https://github.com/naver/kapture/blob/master/kapture_format.adoc#trajectories-txt).
[Camera axis](https://github.com/naver/kapture/blob/master/kapture_format.adoc#4-camera-axis) are the usual in computer vision.

**Comment by kmy8800** [comment]
Thanks for reply, but there seems to be a misunderstanding...

sensors/trajectories.txt is known information of camera and that is used for train or test. Is it right?

What I want to know is this:
When I put an unknown image that is not in dataset(train or test), then how can I get a camera pose of input image?
For example, Indoor navigation in GangNam station(https://www.naverlabs.com/storyDetail/173). 
How to localize camera?

**Comment by kmy8800** [comment]
Close an issue because I think the problem is about colmap function.
