### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by Mukulareddy** [naver/kapture#38]
After the docker is build, I am facing the issue while testing the installation.
Tried upgrading numpy version. but didn't work. Can someone suggest some solution.

/kapture/tools$ python3 ./kapture_print.py -i ../samples/Aachen-Day-Night/kapture/training
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
Traceback (most recent call last):
  File "./kapture_print.py", line 18, in <module>
    import kapture
  File "/home/mukula/kapture/kapture/__init__.py", line 8, in <module>
    from .core import *  # noqa: F401 F403
  File "/home/mukula/kapture/kapture/core/__init__.py", line 7, in <module>
    from .PoseTransform import PoseTransform  # noqa: F401
  File "/home/mukula/kapture/kapture/core/PoseTransform.py", line 9, in <module>
    import quaternion
  File "/home/mukula/.local/lib/python3.8/site-packages/quaternion/__init__.py", line 27, in <module>
    from .numpy_quaternion import (
ImportError: numpy.core.multiarray failed to import

**Comment by jujumo** [comment]
If you are not using docker though, 
https://github.com/moble/quaternion can be a bit tricky to install. 
When you install both latest numpy / numpy-quaternion at the same time for a given python version, you're usually fine. 
But if installing latest numpy, numpy-quaternion must also be updaded to latest
if installing numpy-quaternion on a existing numpy install, you have to manually find the release date of the numpy version and look for a release of numpy-quaternion around the same date.

I hope it helps.

**Comment by Mukulareddy** [comment]
Hello Julien,
Thanks Julien for a very quick response. 
Docker version was the problem. I am able to install the latest version.
