### ISSUE TITLE
Fail to convert from COLMAP to openMVG by using import_colmap and export_openmvg

### ISSUE THREAD

**Issue by petpetpeter** [naver/kapture#39]
Firstly, I would like to ask if it is possible to use these functions to convert the output from COLMAP sparse reconstruction to openMVG sfm_data.json for further reconstruction pipeline (planned to use with openMVS)

I try writing the python script based on these  [tools](https://github.com/naver/kapture/tree/main/tools)
```
from kapture.converter.colmap.import_colmap import import_colmap
from kapture.converter.openmvg.export_openmvg import export_openmvg

logger = logging.getLogger('colmap')

def colmap2kapture(kapture_output_dir,colamp_database_path,colmap_txt_dir,IMAGE_DIR) -> None:
    if not os.path.exists(kapture_output_dir):
        os.makedirs(kapture_output_dir)
    logger.info('importing colmap ...')
    kapture_data = import_colmap(kapture_output_dir,
                                 colamp_database_path,
                                 colmap_txt_dir,
                                 IMAGE_DIR,
                                 )
    logger.info('saving to kapture  ...')
    logger.debug(f'\t"{kapture_output_dir}"')
    kapture.io.csv.kapture_to_dir(kapture_output_dir, kapture_data)

def kapture2openMVG(openMVG_output_dir,kapture_input_dir,IMAGE_DIR):
    export_openmvg(kapture_input_dir,
                   openMVG_output_dir,
                   IMAGE_DIR)
            
if __name__ == '__main__':
    colmap2kapture(kapture_output_dir,colamp_database_path,colmap_txt_dir,IMAGE_DIR)
    kapture2openMVG(openMVG_output_dir,kapture_output_dir,IMAGE_DIR)
```
I was able to get the kapture output and the sfm_data.json file like these
![Screenshot from 2022-04-20 10-41-55](https://user-images.githubusercontent.com/55285546/164130002-7fd366d7-6661-4862-bbe5-50206a08abbd.png)

However, when I try to convert this sfm_data.json to openMVS format with openMVG_main_openMVG2openMVS I found this error
```
ERROR: [sfm_data_io_cereal.cpp:217] JSON Parsing failed - provided NVP (width) not found
ERROR: [main_openMVG2openMVS.cpp:291] The input SfM_Data file "/home/peter/Documents/cpp_workspace/outputs/out_colmap_castle/openMVG/sfm_data.json" cannot be read.
```
what could possibly be the reason?

**Comment by yocabon** [comment]
Hi, sorry for the later answer, do you know what version of openMVG you were using ?

Searching for your error, I dug up https://github.com/openMVG/openMVG/issues/1809
and this pull request [1770](https://github.com/openMVG/openMVG/pull/1770) which seem to have changed the serialization of some camera models for v2.0

**Comment by petpetpeter** [comment]
I used openMVG2.0.
I looked at the repo you dug up and found a hot fixed by replacing the camera intrinsics field with the one exported from sfm_data.bin. I was successfully convert to openMVG format
```
"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483749,
                    "data": {
                        "width": 2048,
                        "height": 1536,
                        "focal_length": 975.0780885651661,
                        "principal_point": [
                            948.9138024627247,
                            713.4183625458142
                        ],
                        "disto_k3": [
                            -0.31088654300585658,
                            0.1015445969542265,
                            -0.013056282653343963
                        ]
                    }}}}],
```
P.S. I would like to ask one more question, is it possible to import only pair match results from COLMAP (without -txt input) and export to openMVG matches file format only.
I tried with
```
python tools/kapture_import_colmap.py -o {kapture_dir} -db {colmap_dir}/database.db -im {images_dir}
```
and successfully import to KAPTURE format
<img src="https://user-images.githubusercontent.com/55285546/166462941-265ffc4f-1cc8-4437-af0e-2d4eedae4dd7.png" width="300" height="200">
but when I try export to openMVG to get matches folder I found this error
```
File "/home/peter/anaconda3/envs/sfm/lib/python3.8/site-packages/kapture/converter/openmvg/export_openmvg.py", line 548, in _export_openmvg_sfm_data
    openmvg_sfm_data_views = _export_openmvg_views(
  File "/home/peter/anaconda3/envs/sfm/lib/python3.8/site-packages/kapture/converter/openmvg/export_openmvg.py", line 318, in _export_openmvg_views
    if timestamp not in kapture_trajectories:
TypeError: argument of type 'NoneType' is not iterable
```
If there is an option to export only the matches file?

**Comment by yocabon** [comment]
1) I added a flag in the exporter "--use_v2_intrinsics_format" to not write "value0" when exporting the intrinsics; I hope it does the trick

2) argument of type 'NoneType' is not iterable
there was definitely a bug here, 
timestamp not in kapture_trajectories -> checks if the image has a pose, but it wasn't considering the case where kapture_trajectories is None (no poses at all)

I fixed this one, though I don't know if what it outputs is actually correct or not.

**Comment by petpetpeter** [comment]
Thank you for the very fast update.
1. I confirm that "--use_v2_intrinsics_format" does the trick. I could convert from Colmap to OpenMVG with this.
2. I could import COLMAP matches and export openMVG matches with the new update. After exporting the matches file, the filter matches from OpenMVG's pipeline seems to work fine.
```
colmap feature_extractor --database_path {colmap_dir}/database.db  --image_path {input_dir}
colmap exhaustive_matcher --database_path {colmap_dir}/database.db"
python tools/kapture_import_colmap.py -o {kapture_dir} -db {colmap_dir}/database.db -im {input_dir}
python tools/kapture_export_openmvg.py -i {kapture_dir} -o {openMVG_dir} --use_v2_intrinsics_format
openMVG_main_GeometricFilter -i {openMVG_dir}/sfm_data.json -m {openMVG_dir}/matches/matches.txt -g f -o {openMVG_dir}/matches/matches.f.bin
openMVG_main_SfM --sfm_engine INCREMENTAL -i {openMVG_dir}/edit.json -m {openMVG_dir}/matches/ -o {openMVG_dir}
```

**Comment by engrkhurramshabbir** [comment]
> Thank you for the very fast update.
> 
> 1. I confirm that "--use_v2_intrinsics_format" does the trick. I could convert from Colmap to OpenMVG with this.
> 2. I could import COLMAP matches and export openMVG matches with the new update. After exporting the matches file, the filter matches from OpenMVG's pipeline seems to work fine.
> 
> ```
> colmap feature_extractor --database_path {colmap_dir}/database.db  --image_path {input_dir}
> colmap exhaustive_matcher --database_path {colmap_dir}/database.db"
> python tools/kapture_import_colmap.py -o {kapture_dir} -db {colmap_dir}/database.db -im {input_dir}
> python tools/kapture_export_openmvg.py -i {kapture_dir} -o {openMVG_dir} --use_v2_intrinsics_format
> openMVG_main_GeometricFilter -i {openMVG_dir}/sfm_data.json -m {openMVG_dir}/matches/matches.txt -g f -o {openMVG_dir}/matches/matches.f.bin
> openMVG_main_SfM --sfm_engine INCREMENTAL -i {openMVG_dir}/edit.json -m {openMVG_dir}/matches/ -o {openMVG_dir}
> ```
I am receiving following error when executing above commands
ERROR   ::openmvg: Fatal error
Traceback (most recent call last):
  File "/home/usr/kapture/tools/kapture_export_openmvg.py", line 114, in <module>
    export_openmvg_command_line()
  File "/home/usr/kapture/tools/kapture_export_openmvg.py", line 98, in export_openmvg_command_line
    export_openmvg(args.kapture,
  File "/home/usr/kapture/kapture/converter/openmvg/export_openmvg.py", line 815, in export_openmvg
    _export_openmvg_sfm_data(
  File "/home/usr/kapture/kapture/converter/openmvg/export_openmvg.py", line 562, in _export_openmvg_sfm_data
    openmvg_sfm_data_views = _export_openmvg_views(
  File "/home/usr/kapture/kapture/converter/openmvg/export_openmvg.py", line 340, in _export_openmvg_views
    prior_t = pose_tr.inverse().t_raw
  File "/home/usr/kapture/kapture/core/PoseTransform.py", line 97, in inverse
    assert self._r is not None
AssertionError

**Comment by jujumo** [comment]
From your backtrace, it seems the prior pose is not fully defined (rotation missing ?).
Can you share some sample data ?
