### ISSUE TITLE
reading binary as a mode="r". Should it be "rb"?

### ISSUE THREAD

**Issue by kodaigit** [naver/kapture#51]
In the following code line, it is expected to read a bin file. But, it seems we are not reading it as binary/. 

https://github.com/naver/kapture/blob/059212d224704c1a888fe9e9e1f92b4a29feefb0/kapture/converter/openmvg/import_openmvg.py#L496

**Comment by yocabon** [comment]
Hi, I believe this only works with 'matches.f.txt'. I remember adding some tool in openMVG so that it would be easy to convert from .bin to .txt: but it's been such a long time it has probably moved https://github.com/openMVG/openMVG/pull/1890.

**Comment by kodaigit** [comment]
right, I was able to produce the text file instead of binary on OpenMVG side. Thank you.
