### ISSUE TITLE
Reproducing the results of Aachen v1.1

### ISSUE THREAD

**Issue by hyBlue** [naver/kapture#6]
Hi, thanks for the great project for building VL pipeline. It is really helpful for my research.
I want to ask some questions for reproducing results of Aachen day night  v1.1.

I'm using off-the-shelf R2D2 and AP-GeM, and would you please share the specific parameters to reproduce the results?

For AP-GeM, [Resnet101-AP-GeM-LM18](https://github.com/almazan/deep-image-retrieval) is used and  
I extract key points using the following [R2D2 script](https://github.com/naver/r2d2/issues/14). 
Also, I'm using config2 in kapture paper for kapture_colmap_build_map.py and kapture_colmap_localize.py, 
Please tell me if I'm doing something wrong above.

And could you please share the number of retrieved images for each query? and also I wonder if you used global bundle adjustment after building the map.

**Comment by yocabon** [comment]
Hi,
for R2D2, you have the correct parameters
```
r2d2_WASF_N8_big.pt

scale-f=2**0.25
min-scale=0.3
max-scale=1
min-size=128
max-size=9999
max-keypoints=40000
reliability-thr=0.7
repeatability-thr=0.7
```
For AP-GeM we used the default parameters
```
Resnet101-AP-GeM-LM18.pt

trfs = ''
pooling='gem'
gemp=3
whiten=None
whitenp=0.5
whitenv=None
whitenm=1.0
```

KAPTURE-R2D2-APGeM should be top 20 (with kapture_compute_image_pairs.py in this repo that'd correspond to --topk=21 when mapping and --topk=20 for the queries).

For kapture_colmap_build_map.py, we use
```
--use-colmap-matches-importer \
--Mapper.ba_refine_focal_length 0 \
--Mapper.ba_refine_principal_point 0 \
--Mapper.ba_refine_extra_params 0
```

For kapture_colmap_localize.py , we use
```
--use-colmap-matches-importer \
--Mapper.ba_refine_focal_length 0 \
--Mapper.ba_refine_principal_point 0 \
--Mapper.ba_refine_extra_params 0 \
--Mapper.min_num_matches 4 \
--Mapper.init_min_num_inliers 4 \
--Mapper.abs_pose_min_num_inliers 4 \
--Mapper.abs_pose_min_inlier_ratio 0.05 \
--Mapper.ba_local_max_num_iterations 50 \
--Mapper.abs_pose_max_error 20 \
--Mapper.filter_max_reproj_error 12
```

The localization code provided in this repository can be seen as a set of examples that should help understanding how the kapture format can be used. 
The results from the paper are not directly computed with this code. However, with the mentioned parameters, you should be able to get very close. Note that there will be a release of more kapture tools coming soon (https://github.com/naver/kapture-localization). This will make reproducing the results easier.
